### ISSUE TITLE
Minor feedback trying to follow along

### ISSUE THREAD

**Issue by martinlindhe** [kidscancode/Godot3_dodge#1]
- The line `$Collision.disabled = false` at
https://github.com/kidscancode/Godot3_dodge/blob/master/Player.gd#L16 this line is not mentioned in the guide (https://godot.readthedocs.io/en/latest/learning/step_by_step/your_first_game.html)

- The line `$Collision.disabled = true` at
 https://github.com/kidscancode/Godot3_dodge/blob/master/Player.gd#L47 is not mentioned, instead `call_deferred("set_monitoring", false)` is suggested with a rationale "you can defer the change, which will tell the game engine to wait until it’s safe to set monitoring to false", is this true?

- The screenshot https://godot.readthedocs.io/en/latest/_images/player_scene_nodes.png has a node named "Collision". The guide doesn't mention naming it like this.

**Comment by rosscg** [comment]
The current iteration does not rename the node, so the guide uses:
`$CollisionShape2D.disabled = false`
rather than:
`$Collision.disabled = false`
I've submitted a pull request to update the code.

**Comment by rosscg** [comment]
Fixed in pending pull request 15: https://github.com/kidscancode/Godot3_dodge/pull/15
