### ISSUE TITLE
Getting an error despite following the instructions correctly

### ISSUE THREAD

**Issue by rolandixor** [kidscancode/Godot3_dodge#16]
I'm getting this error:

Invalid call. Nonexistent function 'set_deferred' in base 'CollisionShape2D' when the player is hit.

**Comment by cbscribe** [comment]
Are you using Godot 3.0? `set_deferred()` was added in 3.1.

**Comment by rolandixor** [comment]
Oh that explains it! I'm using 3.0.x from the Snap Store on Ubuntu. I'll see if it can be updated.
