### ISSUE TITLE
Deathsound is Dead

### ISSUE THREAD

**Issue by dolphy22** [kidscancode/Godot3_dodge#17]
As the title says I can't get the Deathsound to play. Music plays without issue but whenever 'game over' occurs I get  the error: Node not found: DeathSound.

The .wav file is loaded in the streaming box. I listened to and it plays fine in windows. Without the deathsound file the game plays fine. 

Anyone else have this issue?

**Comment by cbscribe** [comment]
If it says "Node not found" then you don't have a node named "DeathSound" in the right location (as a child of the Main node). Check the spelling and the node location.

**Comment by dolphy22** [comment]
Yep a spelling mistake. WTF, my eyes!?!

Thanks.
