### ISSUE TITLE
Mob animation not used

### ISSUE THREAD

**Issue by NikoWil** [kidscancode/Godot3_dodge#2]
In Mob.gd the function

func _process(delta):
	$AnimatedSprite.play()

is missing. As the guide stands the mobs have an animation but it's simply not played.
Thank you for the introductory guide :)

**Comment by ugurstoy** [comment]
Did you activated the playing setting in animated sprite properties?

**Comment by cbscribe** [comment]
As @MahtanSirfalas says, you don't need to do this in code. Click the "Playing" property in the Inspector.
