### ISSUE TITLE
Particles2D node issue

### ISSUE THREAD

**Issue by ugurstoy** [kidscancode/Godot3_dodge#3]
Hello everyone,

When i try to add "particles2d" node and make the settings like the documentation. Player turns to black.

Actually, i couldn't find how can i change the "Visibility Rect" setting to "Rect3"

**Comment by cbscribe** [comment]
A Particles2D doesn't have a Rect3 visibility rect - it's a 2D node. I believe that screenshot is old and needs to be updated.

Regardless, you don't have to change that setting anyway.

**Comment by ugurstoy** [comment]
Yep, after i watch KidsCanCode's video tutorial it's done.. 
cbscribe, Thank you anyway.. 
If someone struggles with that, just watch kidscancode's your first game tutorial on youtube.
