### ISSUE TITLE
Particle2D issue

### ISSUE THREAD

**Issue by yccmd** [kidscancode/Godot3_dodge#7]
Following the tutorial, I added the Particle2D node at the end, but when I imported the playerGrey_up1.png resource as the 'texture' (as shown in the tutorial instructions) I got a particle trail that was twice as big as the Player icon. I know the Player icon had to be scaled to 0.5, 0.5 size, but there was apparently no way to downscale the particle trail to fit the Player icon. Thus, when moving the Player icon in the game, it would leave a trail of fading supersize (2X size) Player icons - very weird.

**Comment by cbscribe** [comment]
In the ParticlesMaterial, there is a `scale` property. Set that to `0.5` (or smaller) to reduce the size of the particles.

**Comment by yccmd** [comment]
Thank you, that did it!
