### ISSUE TITLE
Attempt to call function 'start' in base 'null instance' on a null instance

### ISSUE THREAD

**Issue by KoopHauss** [kidscancode/Godot3_dodge#9]
This is the error I get when I press the "Start" button after running the game. I don't know where I went wrong or how. I used the video on youtube, as well as the Godot Docs step-by-step.

**Comment by cbscribe** [comment]
"null instance" errors occur when you try to access a node that doesn't exist. Usually this is down to misspelling. Since you didn't include the actual error message, I can't tell you where the problem is. Look at the error - it tells you exactly where the problem is.
